name: EffectMaster
version: '${project.version}'
main: me.olios.plugins.effectmaster.EffectMaster
api-version: 1.20

commands:
  effectcontrol:
    aliases:
      - ec
      - econtrol
    usage: /<command> <effect> <level>
    description: admin command to set the player effect level