name: EffectMaster
version: '${project.version}'
main: me.olios.plugins.effectmaster.EffectMaster
api-version: 1.20

commands:
  effectmaster:
    description: Admin command for the EffectMaster plugin.
    aliases:
      - em
      - emaster
    usage: /<command>
    permission: effectmaster.admin
    permission-message: ยง4You don't have permission to do that!

permissions:
  effectmaster.admin:
    default: op
    description: Allows you to use the /effectmaster command